name: Publish CPU images
env:
  LATEST_IMAGE: ghcr.io/luanpaschoal/jupyterlab:latest

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * 1'
  # Run at 03:00 on Monday to update to latest jupyter/docker-stack?
  push:
    # Publish `main` branch as Docker `latest` image.
    branches:
      - main
      # - dev
    paths:
    - 'Dockerfile'
    - 'jupyter_notebook_config.py'
    - 'settings.json'
    - '.github/workflows/docker.yml'
    # # Publish `v1.2.3` tags as release `1.2.3`.
    # tags:
    #   - v*

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      ## Use Actions local caching with buildx
      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Generate image ID and version
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/jupyterlab
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      ## Cache: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
      - name: Build and publish main latest Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          pull: true
          push: true
          tags: ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          # builder: ${{ steps.buildx.outputs.name }}
